site_name: Sematext Documentation
site_url: http://sematext.com/docs
site_favicon: assets/images/favicon.png
pages:
    - Getting Started: index.md
    - Logs:
      - Overview: logs/index.md
      - Sending Log Events: 
        - Overview: logs/sending-log-events.md
        - Using Elasticsearch API: logs/index-events-via-elasticsearch-api.md
        - Logstash: logs/logstash.md
        - Syslog:
          - Overview: logs/syslog.md
          - JSON Messages over Syslog: logs/json-messages-over-syslog.md
          - rsyslog: logs/rsyslog.md
          - syslogd: logs/syslogd.md
          - syslog ng: logs/syslog-ng.md
          - Authorizing IPs for Syslog: logs/authorizing-ips-for-syslog.md
        - JSON: logs/json.md
      - Searching Log Events:
        - Overview: logs/searching-log-events.md
        - Logsene CLI: logs/logsene-cli.md
        - Search Syntax: logs/search-syntax.md
        - Using Elasticsearch API: logs/search-through-the-elasticsearch-api.md
        - Kibana: logs/kibana.md
      - API Reference: logs/logsene-api-reference.md
      - Supported Date Formats: logs/supported-date-formats.md
      - Special Fields: logs/special-fields.md
      - FAQ: logs/faq.md
    - Monitoring:
      - Overview: monitoring/index.md
      - SPM Client:
        - Overview: monitoring/spm-client.md
        - SPM Monitor - Javaagent: monitoring/spm-monitor-javaagent.md
        - SPM Monitor - Standalone: monitoring/spm-monitor-standalone.md
        - SPM Monitor - Switching Modes: monitoring/spm-monitor-switching-modes.md
        - Chef Recipe: monitoring/chef-recipe.md
      - Tag Support: monitoring/tag-support.md
      - Network Map: monitoring/network-map.md
      - Transaction Tracing: monitoring/transaction-tracing.md
      - Database Operations: monitoring/database-operations.md
      - On Demand Profiling: monitoring/on-demand-profiling.md
      - Custom Metrics: monitoring/custom-metrics.md
      - Coda Hale Metrics Reporter: monitoring/coda-hale-metrics-reporter.md
      - API Reference: monitoring/spm-api-reference.md
      - FAQ: monitoring/spm-faq.md
    - Events:
        - Overview: events/index.md
    - Integrations:
        - Overview: integration/index.md
        - Monitoring Akka: integration/akka.md
        - Monitoring Apache: integration/apache.md
        - Monitoring AWS: integration/aws.md
        - Monitoring Cassandra: integration/cassandra.md
        - Monitoring Docker: integration/docker.md
        - Monitoring Elasticsearch: integration/elasticsearch.md
        - Monitoring Hadoop: integration/hadoop.md
        - Monitoring HAProxy: integration/haproxy.md
        - Monitoring HBase: integration/hbase.md
        - Monitoring JVM: integration/jvm.md
        - Monitoring Kafka: integration/kafka.md
        - Monitoring MySQL: integration/mysql.md
        - Monitoring MongoDB: integration/mongodb.md
        - Monitoring Nginx: integration/nginx.md
        - Monitoring Nginx Plus: integration/nginxplus.md
        - Monitoring Node.js: integration/node.js.md
        - Monitoring PHP: integration/php.md
        - Monitoring Redis: integration/redis.md
        - Monitoring Sensei: integration/sensei.md
        - Monitoring Solr: integration/solr.md
        - Monitoring SolrCloud: integration/solrcloud.md
        - Monitoring Spark: integration/spark.md
        - Monitoring Storm: integration/storm.md
        - Monitoring Tomcat: integration/tomcat.md
        - Monitoring ZooKeeper: integration/zk.md
        - HipChat: integration/alerts-hipchat-integration.md
        - PagerDuty: integration/alerts-pagerduty-integration.md
        - Slack: integration/alerts-slack-integration.md
    - Sematext Enterprise:
      - Overview: sematext-enterprise/index.md
      - FAQ: sematext-enterprise/faq.md
    - Sematext Docker Agent: 
        - Overview: sematext-docker-agent/index.md
        - Supported Platforms: sematext-docker-agent/supported-platforms.md
        - Installation: sematext-docker-agent/installation.md
        - Configuration: sematext-docker-agent/configuration.md
        - Troubleshooting: sematext-docker-agent/troubleshooting.md

    - Logagent:
      - Overview: logagent/index.md
      - Installation: 
        - Linux & Mac OS X: logagent/installation.md
        - Windows: logagent/installation-windows.md 
        - Heroku: logagent/installation-heroku.md        
      - Usage: 
        - Command Line Parameters: logagent/cli-parameters.md
        - Configuration: logagent/config-file.md
        - Log Parser Patterns: logagent/parser.md
      - Plugins: 
        - Overview: logagent/plugins.md
        - Input Plugins:
          - Standard input: logagent/input-plugin-stdin.md
          - File input: logagent/input-plugin-files.md
          - Syslog input: logagent/input-plugin-syslog.md
          - Apache Kafka input: logagent/input-plugin-kafka.md
          - InfluxDB input: logagent/input-plugin-influxdb-http.md
          - TCP input: logagent/input-plugin-tcp.md
          - MQTT client input: logagent/input-plugin-mqtt-client.md
          - MQTT broker input: logagent/input-plugin-mqtt-broker.md
          - GELF input: logagent/input-plugin-gelf.md
          - Command input: logagent/input-plugin-command.md
          - Elasticsearch HTTP: logagent/input-plugin-elasticsearch-http.md
          - Elasticsearch query: logagent/input-plugin-elasticsearch-query.md
          - MSSQL query: logagent/input-plugin-mssql.md
          - MySql query: logagent/input-plugin-mysql.md
          - Zeromq input: logagent/input-plugin-zeromq.md
          - Postgresql query: logagent/input-plugin-postgresql.md
          - Apple device location: logagent/logagent-apple-location.md
          - Nova dust sensor: logagent/logagent-novasds.md
          - Cloud Foundry input: logagent/input-plugin-cloudfoundry.md
        - Output Plugins:
          - Standard output: logagent/output-plugin-stdout.md
          - GELF: logagent/output-plugin-gelf.md
          - MQTT: logagent/output-plugin-mqtt.md 
          - Files: logagent/output-plugin-files.md
          - Elasticsearch: logagent/output-elasticsearch.md
          - Amazon Elasticsearch: logagent/output-plugin-aws-elasticsearch.md
          - InfluxDB: logagent/output-plugin-influxdb.md
          - Apache Kafka: logagent/output-plugin-kafka.md
          - Zeromq output: logagent/output-plugin-zeromq.md
          - rTail: logagent/output-plugin-rtail.md
          - Slack webhook: logagent/output-plugin-slack.md
        - Filter Plugins:
          - About filters: logagent/filters.md
          - Grep input filter: logagent/input-filter-grep.md
          - Grok input filter: logagent/input-filter-grok.md
          - SQL output filter: logagent/output-filter-sql.md
          - Access Watch output filter: logagent/output-filter-accesswatch.md
      - FAQ: logagent/faq.md
      - Contributing to Logagent:
          - IDE Integration and debugging: logagent/logagent-ide-conf.md
    - Sematext Cloud API : api/rest-api.md
         

theme:
    name: material
    custom_dir: 'mkdocs-material-custom'
repo_url: https://github.com/sematext/docs/
edit_uri: edit/master/docs/
google_analytics: ['UA-2365268-3', 'mkdocs.org']
site_favicon: 'images/favicon.png'
# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  font:
    text: 'Roboto,sans-serif'
  social:
    - type: 'github'
      link: 'https://github.com/sematext'
    - type: 'twitter'
      link: 'https://twitter.com/sematext'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/sematext-international-llc'
    - type: 'facebook'
      link: 'https://www.facebook.com/Sematext'
    - type: 'google-plus'
      link: 'https://plus.google.com/+SematextGroup'
    - type: 'slideshare'
      link: 'https://www.slideshare.net/sematext'
    - type: 'feed'
      link: 'http://feeds.feedburner.com/SematextBlog'

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'

markdown_extensions:
  - toc(permalink=true)
  - codehilite
  - meta
